/**
 * The handful of values that end up in <head>, the sitemap and the OG card.
 *
 * They live in their own module because they are needed on two sides that
 * cannot see each other's world: the app (Vite, virtual modules, JSX) and
 * `scripts/build-seo.mts` (plain node, run after `vite build` against `dist/`).
 * Anything either side spells out instead of importing from here is a value
 * that quietly goes stale the day the site moves to a custom domain.
 *
 * No trailing slash on SITE_URL — every path is joined as `SITE_URL + "/x"`.
 */
export const SITE_URL = "https://solid-evilcharts.pages.dev";

export const SITE_NAME = "Solid EvilCharts";

export const SITE_TAGLINE =
  "Static, beautifully designed charts for SolidJS, powered by Apache ECharts.";

/**
 * The card image crawlers fetch. Committed under `public/`, regenerated by
 * `pnpm og:build` — see `scripts/build-og.mts`.
 *
 * Absolute, not `/og.png`: Slack, Discord and X all accept relative OG image
 * URLs inconsistently, and the ones that reject it show no image at all.
 */
export const OG_IMAGE = `${SITE_URL}/og.png`;
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

export const GITHUB_URL = "https://github.com/thesambayo/solid-evilcharts";
